### ISSUE TITLE
[LDA] - (Core) Implement bug tracking system

### ISSUE THREAD

**Issue by QuentinCraft** [LuxoriaSoft/Luxoria#55]
**Describe the solution you'd like**
This feature suggests the creation of a bug tracking system, which will be a part of our desktop solution.
This system will be triggered when a crash appears on our solution, This system will be in charge to send the crash event output in issue system. (Github Issues) by using Firebase as a gateway

Tasks : 

- [x]  Create the bug/problem handler, capable of triggering an event in the event of a bug or crash.
- [ ] Ask the user, if Luxoria can send anonymously the bug to our service
- [ ] Develop an API using firebase to catch the issue
- [ ] This API will trigger an event to create an issue on `Luxoria.BugReporting` repository

**Additional context**
Please take into consideration the privacy :
- Anonymized data
- Ask the permission to the user before sending the log
